import useStickerContext from './stickerContext';
import { useSelector } from 'react-redux';
// import { RootState } from '..';
// import { useRoomContext } from 'agora-edu-core';

export const useMusicFunRtmContext = () => {
  // const { usersProfile, teacherProfile } = useSelector((state: RootState) => state.StickerSlice);
  // const { roomInfo } = useRoomContext();
  const {
    subscribeToEmojiStickerSocket,
    subscribeToChatWidget,
    //   subscribeToInstrumentSticker,
    //   subscribeToTeacherEmojiSticker,
    //   subscribeToTeacherInstrumentSticker,
    //   subscribeToTeacherAssignedSticker,
    //   subscribeToTeacherAssignedInstrumentSticker,
    //   unSubscribeToTeacherAssignedInstrumentSticker,
    //   unSubscribeTeacherToInstrumentStickerSocket,
    unSubscribeToEmojiStickerSocket,
    unSubscribeChatWidget,
    //   unSubscribeToInstrumentStickerSocket,
    //   unSubscribeTeacherToEmojiStickerSocket,
    //   unSubscribeToTeacherAssignedSticker,
    //   publishToTeacherAssignedInstrumentSticker,
    publishStickerEmojiToSocket,
    subscribeToSticker,
    publishStickerToSocket,
    publishChatWidget,
    //   publishStickerTeacherInstrumentToSocket,
    //   publishStickerTeacherEmojiToSocket,
    //   publishStickerInstrumentToSocket,
    //   publishToTeacherAssignedSticker,
    //   addUserProfile,
    //   addTeacherProfile,
    //   addOrRemoveUserEmoji,
    //   addOrRemoveUserInstrument,
    //   addOrRemoveTeacherEmoji,
    //   addOrRemoveTeacherInstruments,
  } = useStickerContext();
  return {
    //   roomInfo,
    //   usersProfile,
    //   teacherProfile,
    subscribeToEmojiStickerSocket,
    subscribeToSticker,
    publishStickerToSocket,
    subscribeToChatWidget,
    //   subscribeToTeacherAssignedSticker,
    //   subscribeToInstrumentSticker,
    //   subscribeToTeacherEmojiSticker,
    //   subscribeToTeacherInstrumentSticker,
    //   subscribeToTeacherAssignedInstrumentSticker,
    //   unSubscribeToTeacherAssignedInstrumentSticker,
    //   unSubscribeTeacherToInstrumentStickerSocket,
    unSubscribeToEmojiStickerSocket,
    unSubscribeChatWidget,
    //   unSubscribeToTeacherAssignedSticker,
    //   unSubscribeToInstrumentStickerSocket,
    //   unSubscribeTeacherToEmojiStickerSocket,
    publishStickerEmojiToSocket,
    publishChatWidget,
    //   publishToTeacherAssignedSticker,
    //   publishStickerTeacherInstrumentToSocket,
    //   publishToTeacherAssignedInstrumentSticker,
    //   publishStickerTeacherEmojiToSocket,
    //   publishStickerInstrumentToSocket,
    //   addUserProfile,
    //   addTeacherProfile,
    //   addOrRemoveUserEmoji,
    //   addOrRemoveUserInstrument,
    //   addOrRemoveTeacherEmoji,
    //   addOrRemoveTeacherInstruments,
  };
};
